name: Hedera Mirror Node Explorer End-to-end Tests

on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*, 16.14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run serve:prod
          wait-on: "http://localhost:38920"
          spec: tests/e2e/specs/*
